_wandb:
    value:
        cli_version: 0.21.0
        e:
            s47ge3d2dchwfaipglfamgccfgx15qwg:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                codePath: train/clip_finetune.py
                codePathLocal: clip_finetune.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "170402336768"
                email: chiragvaghela10@ymail.com
                executable: /Users/chiragvaghela/PycharmProjects/lidar_vqa/.venv/bin/python
                git:
                    commit: c9eab50ab3c594233e3028d6b11f5b1a69d92df1
                    remote: https://github.com/ChiragVaghela10/lidar_vqa.git
                host: Chirags-MacBook-Pro.local
                memory:
                    total: "25769803776"
                os: macOS-15.5-arm64-arm-64bit-Mach-O
                program: /Users/chiragvaghela/PycharmProjects/lidar_vqa/train/clip_finetune.py
                python: CPython 3.13.0
                root: /Users/chiragvaghela/PycharmProjects/lidar_vqa/train
                startedAt: "2025-07-06T22:53:46.561663Z"
                writerId: s47ge3d2dchwfaipglfamgccfgx15qwg
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.0
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
        visualize:
            val/confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: val/confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
batch_size:
    value: 32
dropout:
    value: 0.3
epochs:
    value: 1
freeze_clip:
    value: true
fusion:
    value: late
hidden_dim:
    value: 256
lr:
    value: 0.001
model:
    value: ViT-B/32 + MLP head
